### ISSUE TITLE
Problem running Python script on macOS

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#232]
The problem in #180 may well be because of added security measures in macOS Mojave (10.14.4). Having got to the point where I can load up the dylibs for `check_same_operands.py`[1], I now get this
```
$ PYTHONPATH=/opt/adalang/python ~/adacore/libadalang/contrib/check_same_operands.py *.ad?
Traceback (most recent call last):
  File "/Users/simon/adacore/libadalang/contrib/check_same_operands.py", line 12, in <module>
    import libadalang as lal
  File "/opt/adalang/python/libadalang/__init__.py", line 9275, in <module>
    ], ctypes.c_int)
  File "/opt/adalang/python/libadalang/__init__.py", line 88, in _import_func
    func = getattr(_c_lib, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fe16ed0f280, ada_ada_node_p_expression_type): symbol not found
```
Looking at :9275, it is indeed looking for `ada_ada_node_p_expression_type`, which is missing from `libadalang.dylib`: the one before, `ada_ada_node_is_ghost` **is** present, the one after, `ada_ada_node_p_referenced_decl`, isn’t.

[1]: by massive rewriting of the `@rpath/libname.dylib` references in the referring dylib to use the actual path to the required dylib, using `install_name_tool -change`. Will think some more about this, in a different issue I expect.

**Comment by simonjwright** [comment]
Can’t now reproduce. Obviously I managed to have the wrong version of something in there.
Having much less trouble with GNAT CE 2018, though even as a Mac fan I have to say Darwin’s dynamic loading is -- baffling.
