### ISSUE TITLE
cannot pass the "generate" stage

### ISSUE THREAD

**Issue by jotd666** [AdaCore/libadalang#3]
python ada/manage.py generate

gives me:

[95mGenerating source for libadalang ...[0m
[94mCompiling the grammar...[0m
File "[96mK:\temp\ada\language\ast.py[0m", line [96m3275[0m, in BlockStmt._env_key_44
  line [96m3282[0m, in FieldAccess expression
    [1m[91mError[0m: SymbolType values have no field (accessed field was to_array)
[91mErrors, exiting[0m

**Comment by jotd666** [comment]
I'm using python 2.7.9. Do I need a newer python?

**Comment by jotd666** [comment]
upgraded to python 2.7.12: same result.

**Comment by pmderodat** [comment]
Hi @jotd666,

Python 2.7 (whatever the minor version) is fine. What I suspect instead is that you have an outdated Langkit repository: the “to_array” method for symbols has been added last week. Can you update your Langkit clone and re-try?

Thank you in advance,

**Comment by raph-amiard** [comment]
Hi @jotd666,

Additionally, if you installed langkit in your python env via `setup.py install`, or by installing libadalang's REQUIREMENTS.txt file, you might want to reinstall langkit in your env after upgrading. Tell us how it goes !

Kind regards

**Comment by jotd666** [comment]
I reinstalled and now I get:

Traceback (most recent call last):
  File "C:\python27\lib\site-packages\langkit\libmanage.py", line 464, in run
    parsed_args.func(parsed_args)
  File "C:\python27\lib\site-packages\langkit\libmanage.py", line 216, in internal
    self.set_context(*args, **kwargs)
  File "C:\python27\lib\site-packages\langkit\libmanage.py", line 489, in set_context
    self.context = self.create_context(parsed_args)
  File "ada/manage.py", line 86, in create_context
    from language.grammar import ada_grammar
  File "K:\temp\ada\language\grammar.py", line 5, in <module>
    from language.ast import *
  File "K:\temp\ada\language\ast.py", line 19, in <module>
    from langkit.expressions.logic import (
ImportError: cannot import name LogicAnd
[91mInternal error! Exiting[0m

**Comment by jotd666** [comment]
worked all right, thanks
