### ISSUE TITLE
Missing elsif

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/libadalang#44]
It seems that `elsif` isn’t covered in an if-expression:
```
Traceback (most recent call last):
  File "check_test_not_null.py", line 317, in <module>
    main(parser.parse_args())
  File "check_test_not_null.py", line 313, in main
    do_file(f)
  File "check_test_not_null.py", line 308, in do_file
    explore(f, subp)
  File "check_test_not_null.py", line 295, in explore
    traverse_subp_body(subp, {})
  File "check_test_not_null.py", line 293, in traverse_subp_body
    traverse(sub, nulls)
  File "check_test_not_null.py", line 287, in traverse
    traverse(sub, nulls)
  File "check_test_not_null.py", line 287, in traverse
    traverse(sub, nulls)
  File "check_test_not_null.py", line 218, in traverse
    traverse(sub, nulls)
  File "check_test_not_null.py", line 287, in traverse
    traverse(sub, nulls)
  File "check_test_not_null.py", line 245, in traverse
    for sub in node.f_elsif_list:
AttributeError: 'IfExpr' object has no attribute 'f_elsif_list'
```

**Comment by raph-amiard** [comment]
Hello Simon,

I gather from the traceback that you're talking specifically about the check_test_not_null script ?

**Comment by simonjwright** [comment]
On 10 Dec 2017, at 12:55, Raphaël AMIARD <notifications@github.com> wrote:
> Hello Simon,
> 
> I gather from the traceback that you're talking specifically about the check_test_not_null script ?
> 

Yes, indeed. All the other scripts were fine with my source (Certyflie, actually)

**Comment by raph-amiard** [comment]
Ok, I did assign the issue to Yannick that developed this script. I'm not going to fix it myself probably :) If you want to take a stab at it it should not be too hard. Else we'll have to wait for @yannickmoy !

**Comment by yannickmoy** [comment]
At this stage, these checkers are only examples of use of Libadalang. The new infrastructure for checkers is developed in https://github.com/AdaCore/lal-checkers, under checker "dead_code" which is on review with you Raph. :-) The new infrastructure shares all the boilerplate to traverse the AST, so won't suffer from the same bug.

**Comment by raph-amiard** [comment]
Ok !
