### ISSUE TITLE
DottedName.full_name raise AttributeError when its suffix is a StringLiteral operator name

### ISSUE THREAD

**Issue by ludogauthier** [AdaCore/libadalang#56]
Getting the "full_name" on a DottedName which suffix is a StringLiteral operator name raise
the exception AttributeError.

```Ada
#!/usr/bin/env python
# encoding: utf-8

import libadalang as lal

str2ada_ctx = lal.AnalysisContext('utf-8')
def str2ada(string):
    unit = str2ada_ctx.get_from_buffer("", string)
    if unit.diagnostics:
        raise Exception("libadalang Diagnostics: " + "\n".join(map(str, unit.diagnostics)))
    unit.populate_lexical_env()
    return unit.root


dottedname = str2ada('procedure p is I:Integer; begin I := Standard. "+"(3,4); end;').findall(lal.DottedName)[0];
print dottedname.text
print dottedname.full_name
```
```Python
Standard. "+"
Traceback (most recent call last):
  File "./pb.py", line 21, in <module>
    print dottedname.full_name
  File "/usr/gnat/2017-gpl/python/libadalang.py", line 7711, in full_name
    return "{}.{}".format(n.f_prefix.full_name, n.f_suffix.full_name)
AttributeError: 'StringLiteral' object has no attribute 'full_name'
```

**Comment by raph-amiard** [comment]
Hey @ludogauthier this is now fixed :)

**Comment by ludogauthier** [comment]
Great, Thanks !
